"""
Django settings for Depression project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=s8hdb7)bf&vjksv72ew^8qu)q$4ax&7tx*$_g-mzq1j3wn+-7'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "simpleui",

    # 'multi_captcha_admin',
    'django.contrib.admin',
    'captcha',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    # 'django.middleware.locale.LocaleMiddleware',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 自己的App
    'Question_Bank.apps.QuestionBankConfig',
    'Comprehensive.apps.ComprehensiveConfig',
    'Article.apps.ArticleConfig',
    # 'django.contrib.admindocs',
    'CommUtils.apps.CommutilsConfig',
    'mdeditor',
    # 注册自己的模版tag
    'Comprehensive.templatetags',
]
MDEDITOR_CONFIGS = {
    'default': {
        'width': 1000,  # 自定义编辑框宽度
        'heigth': 500,  # 自定义编辑框高度
    }
}
AUTH_USER_MODEL = "auth.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'Depression.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django.template.context_processors.media',
            ], 'builtins': ['django.templatetags.static'],
        },
    },
]

WSGI_APPLICATION = 'Depression.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""

# 外接数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'depression',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'  # 中文支持      'en-us' #英文

TIME_ZONE = 'Asia/Shanghai'  # 东八区时间      'UTC' # 美国时间

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 时差问题    当true 时 会相差8个小时

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),

)

# 设置上传目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# 设置前缀
MEDIA_URL = '/media/'

# #配置SIMPLEUI_ICON
SIMPLEUI_ICON = {
    '等级详情': 'fa fa-align-left',  # 键为界面显示的菜单名称，值为https://fontawesome.com/icons/tag?style=regular中图标的class值
    '试题管理': 'fa fa-book-reader',
    '试题分类': 'fas fa-bookmark',
    '分类管理': 'fas fa-layer-group',
    '访问记录': 'fa fa-eye',
    '用户信息详情': 'far fa-user-circle',
    '综合管理': 'fab fa-asymmetrik',
    '信息管理': 'fas fa-info-circle',
    "图片管理": 'fas fa-images',
    # 'Categorys':'fas fa-tags'
}
# 自定义simpleui 菜单
SIMPLEUI_CONFIG = {
    # 在自定义菜单的基础上保留系统模块
    'system_keep': True,
    'menus': [{
        'name': '数据详情',
        'icon': 'fas fa-yin-yang',
        'models': [{
            'name': '问卷折线图统计',
            'icon': 'fas fa-chart-line',
            'url': 'admin/LineCharts'
        }, {
            'name': '答卷详情',
            'icon': 'far fa-chart-bar',
            'url': 'admin/Histogram/'
        }]
    }, ]
}
"""菜单栏右侧"""
SIMPLEUI_HOME_INFO = False
