# Generated by Django 2.2 on 2021-04-07 19:53

import django.utils.timezone
import mdeditor.fields
from django.db import migrations, models

import Comm.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Comprehensive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='分类名')),
                ('create_operator',
                 models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='创建者')),
                ('update_operator',
                 models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='修改者')),
                ('create_time',
                 models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='标题')),
                ('image',
                 models.ImageField(storage=Comm.storage.ImageStorage(), upload_to='upload/WebImg/Article/%Y%m%d',
                                   verbose_name='图片')),
                ('content_raw', mdeditor.fields.MDTextField(verbose_name='原始内容')),
                ('content_render', models.TextField(blank=True, null=True, verbose_name='呈现内容')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='作者')),
                ('slug', models.SlugField(editable=False, max_length=500, verbose_name='Url')),
                ('reading', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='阅读次数')),
                ('create_operator',
                 models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='创建者')),
                ('update_operator',
                 models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='修改者')),
                ('create_time',
                 models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('NavMeun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='Comprehensive.NavManager', verbose_name='所属菜单')),
                ('category',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article.Category',
                                   verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章管理',
                'ordering': ('-create_time', '-update_time'),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
