# Generated by Django 2.2 on 2021-05-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reading',
            field=models.PositiveIntegerField(blank=True, default=636, editable=False, null=True, verbose_name='阅读次数'),
        ),
    ]
