# Generated by Django 2.2 on 2021-05-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20210506_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reading',
            field=models.PositiveIntegerField(blank=True, default=698, editable=False, null=True, verbose_name='阅读次数'),
        ),
    ]
