# Generated by Django 2.2 on 2021-04-07 19:53

import django.contrib.auth.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import Comm.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('gender', models.CharField(blank=True, max_length=60, null=True, verbose_name='性别')),
                ('grade', models.CharField(blank=True, max_length=60, null=True, verbose_name='年级')),
                ('HeadImg', models.ImageField(blank=True, height_field='image_height', null=True,
                                              storage=Comm.storage.ImageStorage(), upload_to='upload/HeadImg/%Y%m%d',
                                              verbose_name='头像', width_field='image_width')),
                ('create_time',
                 models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='注册时间')),
                ('image_height', models.PositiveIntegerField(blank=True, default='325', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='520', editable=False, null=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '信息管理',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
