# Generated by Django 2.2 on 2021-05-06 23:57

import Comm.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Comprehensive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='image_height', storage=Comm.storage.ImageStorage(),
                                    upload_to='upload/WebImg/SlideImg/%Y%m%d', verbose_name='图片',
                                    width_field='image_width'),
        ),
    ]
