# Generated by Django 2.2 on 2021-05-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Comprehensive', '0002_auto_20210506_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='MacAdress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='OutIP',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='来访IP'),
        ),
    ]
